### ISSUE TITLE
Make Online

### ISSUE THREAD

**Issue by DQ318** [razzie/raztalk#1]
Hi, @razzie !

I was able to compile and start the tests on your project and would like to know how do I put that char on a server and make it accessible to other users just like you did at https://talk.gorzsony.com?

Cheers.

**Comment by razzie** [comment]
Hi @DQ318 !

If you compiled with Visual Studio you should have a folder with raztalk.exe and all the necessary libraries. You can copy the content of that folder and if you have linux server, you can run it with "mono raztalk.exe".
By default it will listen on port 8888 but you can either change the code or use a service like nginx to redirect the traffic to it.

I hope it helps.

Cheers
